FROM python:3.7-alpine

WORKDIR .

RUN apk add --no-cache gcc musl-dev linux-headers geos libc-dev postgresql-dev build-base python3-dev
COPY requirements.txt requirements.txt
RUN python3 -m pip install -U pip
RUN pip3 install --upgrade setuptools
RUN pip install -r requirements.txt

EXPOSE 5000

COPY . .
CMD ["flask", "run", "--host", "0.0.0.0"]